FROM golang:1.24

WORKDIR /app

# Copy go.mod and go.sum first to cache deps
COPY go.mod go.sum ./

RUN go mod download

# Copy the rest of the source code
COPY . .

# Build the Go binary
RUN go build -o passwordgen main.go

# Run the compiled Go program
ENTRYPOINT ["/app/passwordgen"]